# -*- coding: utf-8 -*-
"""Healthcare.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mn3rYtNmwJgKg0Qsq6EqZPxYk-9672BS
"""

!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
!pip install torchxrayvision
!pip install pydicom opencv-python pillow tqdm matplotlib seaborn scikit-learn
!pip install grad-cam

!pip install torch torchvision pillow matplotlib

import torch
import torch.nn as nn
from torchvision import models, transforms
import matplotlib.pyplot as plt
from PIL import Image
import torch.nn.functional as F

!pip install torch torchvision pandas pillow matplotlib scikit-learn

import os
import pandas as pd
from PIL import Image
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import models, transforms
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix

df = pd.read_csv(r'Chest_xray_Corona_Metadata.csv')
print(df.head())

df['Label'] = df['Label'].apply(lambda x: 0 if x == "Normal" else 1)
df['Dataset_type'] = df['Dataset_type'].str.upper()
print(df['Label'].value_counts())  # Ensure 2 classes exist for training

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

class XrayDataset(Dataset):
    def __init__(self, dataframe):
        self.df = dataframe

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img_path = os.path.join(images_dir, row['X_ray_image_name'])
        img = Image.open(img_path).convert("RGB")
        img = transform(img)

        label = torch.tensor(row['Label'], dtype=torch.float32)
        return img, label

train_df = df[df['Dataset_type'] == "TRAIN"]
test_df  = df[df['Dataset_type'] == "TEST"]

train_data = XrayDataset(train_df)
test_data  = XrayDataset(test_df)

train_loader = DataLoader(train_data, batch_size=16, shuffle=True)
test_loader  = DataLoader(test_data, batch_size=16, shuffle=False)

print(f"Train: {len(train_data)}  | Test: {len(test_data)}")

model = models.mobilenet_v2(weights=models.MobileNet_V2_Weights.DEFAULT)
model.classifier[1] = nn.Linear(model.last_channel, 1)

device = "cuda" if torch.cuda.is_available() else "cpu"
model = model.to(device)

criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)

print("✅ Model Ready on", device)

epochs = 5

for epoch in range(epochs):
    model.train()
    running_loss = 0.0

    for imgs, labels in train_loader:
        imgs, labels = imgs.to(device), labels.to(device).unsqueeze(1)

        optimizer.zero_grad()
        outputs = model(imgs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    print(f"Epoch [{epoch+1}/{epochs}] Loss: {running_loss/len(train_loader):.4f}")

print("✅ Training Complete")

!pip install torch torchvision pandas pillow matplotlib scikit-learn --quiet

from google.colab import files, output
uploaded = files.upload()  # upload normal.jpeg and pneumonia.jpeg

print("Uploaded:", list(uploaded.keys()))

from google.colab import files, output
uploaded = files.upload()  # upload normal.jpeg and pneumonia.jpeg

print("Uploaded:", list(uploaded.keys()))

import os, shutil

images_dir = "/content/images"
os.makedirs(images_dir, exist_ok=True)

for fname in uploaded.keys():
    shutil.move(f"/content/{fname}", f"{images_dir}/{fname}")

print("Images placed in:", images_dir, "->", os.listdir(images_dir))

import pandas as pd

rows = []
for fn in sorted(os.listdir(images_dir)):
    lower = fn.lower()
    if "normal" in lower:
        label_txt = "Normal"
    elif "pneumonia" in lower:
        label_txt = "Pneumonia"
    else:
        # fallback (treat as Normal); change if needed
        label_txt = "Normal"
    rows.append({
        "X_ray_image_name": fn,
        "Label": label_txt,
        "Dataset_type": "TRAIN",              # we’ll duplicate to TEST below
        "Label_2_Virus_category": "",
        "Label_1_Virus_category": ""
    })

df = pd.DataFrame(rows)

# also create a TEST split by copying the rows (so we can run evaluation)
test_df = df.copy()
test_df["Dataset_type"] = "TEST"

df_all = pd.concat([df, test_df], ignore_index=True)
csv_path = "/content/labels.csv"
df_all.to_csv(csv_path, index=False)
print("CSV saved at:", csv_path)
df_all

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import models, transforms
from PIL import Image

# Encode labels: Normal -> 0, anything else -> 1
df_all = pd.read_csv(csv_path)
df_all["Label_enc"] = df_all["Label"].apply(lambda x: 0 if str(x).strip().lower()=="normal" else 1)

train_df = df_all[df_all["Dataset_type"]=="TRAIN"].reset_index(drop=True)
test_df  = df_all[df_all["Dataset_type"]=="TEST"].reset_index(drop=True)

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225]),
])

class XrayDataset(Dataset):
    def __init__(self, dataframe, root_dir, transform=None):
        self.df = dataframe
        self.root_dir = root_dir
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img_path = os.path.join(self.root_dir, row["X_ray_image_name"])
        img = Image.open(img_path).convert("RGB")
        if self.transform:
            img = self.transform(img)
        label = torch.tensor(row["Label_enc"], dtype=torch.float32)
        return img, label

train_ds = XrayDataset(train_df, images_dir, transform)
test_ds  = XrayDataset(test_df,  images_dir, transform)

train_loader = DataLoader(train_ds, batch_size=2, shuffle=True)
test_loader  = DataLoader(test_ds,  batch_size=2, shuffle=False)

print(f"Train size: {len(train_ds)}, Test size: {len(test_ds)}")

device = "cuda" if torch.cuda.is_available() else "cpu"

model = models.mobilenet_v2(weights=models.MobileNet_V2_Weights.DEFAULT)
model.classifier[1] = nn.Linear(model.last_channel, 1)
model = model.to(device)

criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

print("Ready on", device)

epochs = 2
for epoch in range(epochs):
    model.train()
    loss_sum = 0.0
    for imgs, labels in train_loader:
        imgs = imgs.to(device)
        labels = labels.unsqueeze(1).to(device)

        optimizer.zero_grad()
        logits = model(imgs)
        loss = criterion(logits, labels)
        loss.backward()
        optimizer.step()

        loss_sum += loss.item()
    print(f"Epoch {epoch+1}/{epochs} - Loss: {loss_sum/len(train_loader):.4f}")

print("Training complete ✅")

import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

model.eval()
y_true, y_pred = [], []

with torch.no_grad():
    for imgs, labels in test_loader:
        imgs = imgs.to(device)
        logits = model(imgs)
        probs = torch.sigmoid(logits).cpu().numpy().flatten()
        preds = (probs > 0.5).astype(int)
        y_true.extend(labels.numpy().astype(int).tolist())
        y_pred.extend(preds.tolist())

print("Confusion Matrix:")
print(confusion_matrix(y_true, y_pred))
print("\nReport:")
print(classification_report(y_true, y_pred, target_names=["Normal","Pneumonia"]))

import matplotlib.pyplot as plt

def predict_image(path):
    img = Image.open(path).convert("RGB")
    x = transform(img).unsqueeze(0).to(device)
    with torch.no_grad():
        prob = torch.sigmoid(model(x)).item()
    pred = "Pneumonia" if prob>0.5 else "Normal"
    return img, pred, prob

fig, axes = plt.subplots(1, len(os.listdir(images_dir)), figsize=(10,4))
if len(os.listdir(images_dir)) == 1:
    axes = [axes]

for ax, fn in zip(axes, sorted(os.listdir(images_dir))):
    img, pred, prob = predict_image(os.path.join(images_dir, fn))
    ax.imshow(img); ax.axis("off")
    ax.set_title(f"{fn}\nPred: {pred} ({prob:.2f})")

plt.tight_layout(); plt.show()

!pip install pandas matplotlib seaborn --quiet

from google.colab import files
uploaded = files.upload()

csv_path = list(uploaded.keys())[0]
print("Loaded:", csv_path)

import pandas as pd

df = pd.read_csv(csv_path)
print(df.head())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(5,4))
sns.countplot(x=df["Label"])
plt.title("Distribution of Labels")
plt.xlabel("Label")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(5,4))
sns.countplot(x=df["Dataset_type"])
plt.title("Dataset Type Distribution")
plt.xlabel("Dataset Type")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(data=df, x="Label", hue="Dataset_type")
plt.title("Label Count by Dataset Split")
plt.xlabel("Label")
plt.ylabel("Count")
plt.show()

virus_cols = ["Label_1_Virus_category", "Label_2_Virus_category"]

for col in virus_cols:
    if col in df.columns and df[col].notna().any():
        plt.figure(figsize=(5,4))
        sns.countplot(x=df[col].fillna("Unknown"))
        plt.title(f"Distribution: {col}")
        plt.xlabel(col)
        plt.ylabel("Count")
        plt.xticks(rotation=45)
        plt.show()

print("\nLabel Counts:\n", df["Label"].value_counts())
print("\nDataset Type Counts:\n", df["Dataset_type"].value_counts())
print("\nCrosstab:\n", pd.crosstab(df["Dataset_type"], df["Label"]))

!pip install pandas matplotlib seaborn --quiet

from google.colab import files
uploaded = files.upload()   # Upload your CSV here

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

csv_path = list(uploaded.keys())[0]
df = pd.read_csv(csv_path)

# Normalize
df["Label"] = df["Label"].astype(str).str.strip()
df["Dataset_type"] = df["Dataset_type"].astype(str).str.upper().str.strip()

# ✅ Missing label check
df["Missing_Label"] = df["Label"].replace("", np.nan).isna()
missing_count = df["Missing_Label"].sum()
print(f"\n❗ Missing label rows: {missing_count}")

if missing_count > 0:
    print(df[df["Missing_Label"]])

plt.figure(figsize=(6,6))
df["Label"].value_counts().plot(
    kind="pie", autopct="%1.1f%%", startangle=90, shadow=True
)
plt.title("Label Distribution")
plt.ylabel("")
plt.show()

ctab = pd.crosstab(df["Dataset_type"], df["Label"])
plt.figure(figsize=(6,6))
ctab.T.plot(
    kind="pie", subplots=True, autopct="%1.1f%%", startangle=90, legend=False
)
plt.suptitle("Label Distribution within each Dataset Split")
plt.show()

print("\nLabel Counts:\n", df["Label"].value_counts())
print("\nDataset Split Counts:\n", df["Dataset_type"].value_counts())
print("\nCrosstab Table:\n", ctab)

label_counts = df["Label"].value_counts()

if len(label_counts) > 1:
    minority = label_counts.min()
    majority = label_counts.max()
    imbalance_ratio = minority / majority

    print("\n🔍 Class Imbalance Check:")
    print(label_counts)
    print(f"Imbalance Ratio = {imbalance_ratio:.2f}")

    if imbalance_ratio < 0.5:
        print("⚠️ WARNING: Dataset is highly imbalanced!")
        print("➡ Consider augmentation / resampling for training")
    else:
        print("✅ Class balance looks healthy")
else:
    print("\n⚠️ Dataset contains only ONE class — model cannot learn to classify!")

